### ISSUE TITLE
New ruby hash syntax and SymbolOperator

### ISSUE THREAD

**Issue by disbelief** [mongomapper/plucky#39]
Wondering if there's any way to get Plucky's SymbolOperator to work with Ruby's new hash syntax?

For example is there a way to get:

``` ruby
People.where :created_at.lt => Time.now
```

to use the form:

``` ruby
People.where created_at: Time.now
```

but somehow apply the `.lt` operator? 

Having the two forms sprinkled throughout a codebase, depending on whether I need an operator or not, is really messy.

**Comment by sethjeffery** [comment]
You could do something like this:

```ruby
class GtExt
  def [](val)
    {:$gt => val}
  end
end

$gt = GtExt.new

People.where created_at: $gt[Time.now]
```

Or you could be *really* hacky and add it right into Kernel

```
module Kernel
  def GreaterThan(val)
    { :$gt => val }
  end
end

People.where created_at: GreaterThan Time.now
```

Right-wing coders might disapprove though. :smile:

**Comment by smtlaissezfaire** [comment]
Closing this one out.  It's a Ruby syntax issue.  Open question: should we remove #lt, #lte, etc?  If we do, we'll need to provide some syntax translation code.
