### ISSUE TITLE
Access to repo?

### ISSUE THREAD

**Issue by smtlaissezfaire** [mongomapper/plucky#43]
@cheald I can't seem to push to plucky.  Can you add me as a contributor?

**Comment by cheald** [comment]
Done!

**Comment by smtlaissezfaire** [comment]
Thanks.  I've got some stuff to push but I'll send you a patch review first.

**Comment by smtlaissezfaire** [comment]
I couldn't push a new gem version to rubygems.  Can you provide access?  scott@railsnewbie.com

**Comment by smtlaissezfaire** [comment]
Thanks in advance @cheald

**Comment by cheald** [comment]
You should have access now!

**Comment by smtlaissezfaire** [comment]
Thanks @cheald.  I just released plucky 0.7.0.  I'm also going to release mongomapper 0.14.0 RC 1 in a moment.
