### ISSUE TITLE
Any chance plucky will work with the new (2.x) mongo driver more or less as is?

### ISSUE THREAD

**Issue by bughit** [mongomapper/plucky#46]
or does it require major changes?

**Comment by bughit** [comment]
@smtlaissezfaire could you please comment?

**Comment by smtlaissezfaire** [comment]
Hi @bughit I haven't done any work on upgrading, but I expect a lot of internals of plucky will have to change.  I don't expect many of the APIs to change, though.

You can check out this patch: https://github.com/mongomapper/mongomapper/pull/638/files which is incomplete, but shows the sorts of changes that will be needed in mongo_mapper and plucky.

Hope that helps!
